# Generated by Django 4.2.5 on 2023-11-01 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_alter_post_comment_count_alter_post_like_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows_count",
        ),
    ]
