# Generated by Django 4.2.5 on 2023-12-01 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_post_updated_at_post_updated_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="like",
            new_name="liked_posts",
        ),
    ]
